# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meli_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('currency_id', models.CharField(max_length=200)),
                ('pictures', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=200)),
                ('publisher_name', models.CharField(max_length=200)),
                ('publisher_phone', models.CharField(max_length=200)),
                ('publisher_email', models.CharField(max_length=200)),
            ],
        ),
    ]
