# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='meli_link',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='publisher_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='publisher_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='publisher_phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
