# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-30 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161029_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='publisher_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
