# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-30 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_properties_publisher_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='location',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pictures',
            field=models.CharField(max_length=10000),
        ),
    ]
