# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20161030_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
