# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-30 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20161030_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='meli_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='properties',
            name='meli_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='properties',
            name='publisher_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='publisher_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='publisher_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='publisher_phone',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
