# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20161030_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='bathrooms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bedrooms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='built_square_meters',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='total_square_meters',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
